name: "Frogbot Scan and Fix"
on:
  push:
    branches: [ "main", "byron-test" ]
permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write
jobs:
  create-fix-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest

      - uses: jfrog/frogbot@v2
     #   with:
     #     oidc-provider-name: "byron-juice-shop"
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
